Fixed reference to types in package.json
I'm receiving an error for missing references to any `.d.ts` file for this package. I noticed that its referring to what appears to be an old index.d.ts file. Adjusted it to refer ./types/app-configuration.d.ts
```
error TS7016: Could not find a declaration file for module '@azure/app-configuration'. 'C:/src/appconfiguration-express/node_modules/@anfiguration/dist/index.js' implicitly has an 'any' type.
  Try `npm install @types/azure__app-configuration` if it exists or add a new declaration (.d.ts) file containing `declare module '@azure/app-configuration';`

2 import { AppConfigurationClient } from "@azure/app-configuration";
                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~
```